apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        imagePullPolicy: Always
        image: ghcr.io/yashu-x/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: ALLOWED_ORIGINS
          value: "http://127.0.0.1:8000,http://localhost:8000,http://backend-service:8000,http://frontend-service:3000"
        - name: JWT-SECRET
          value: "1234"
        - name: PORT
          value: "8000"
        - name: MONGO_URI
          value: "mongodb+srv://nthashenu:HfiVenxioFIpVb2T@k8sclusterr.wjwznhn.mongodb.net/"



