apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: ghcr.io/yashu-x/frontend:latest
        ports:
        - containerPort: 4173
        env:
        - name: BACKEND_BASE_URL
          value: "http://127.0.0.1:8000/"